import Link from 'next/link'
import { AppLogo } from '@/components/AppLogo'
import { ArrowLeft, Scale, Calendar, Mail } from 'lucide-react'

export const metadata = {
  title: 'Terms of Service — NatureQuery',
}

const sections = [
  {
    number: '01',
    title: 'Acceptance of Terms',
    content: 'By accessing or using NatureQuery ("Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.',
  },
  {
    number: '02',
    title: 'Description of Service',
    content: 'NatureQuery is a SaaS platform that converts natural language questions into SQL queries, executes them against user-provided databases, and exports the results. The Service includes AI-powered query generation, data visualization, team collaboration, and export functionality.',
  },
  {
    number: '03',
    title: 'User Accounts',
    content: 'You must provide accurate information when creating an account. You are responsible for maintaining the confidentiality of your credentials and for all activity under your account. Notify us immediately of any unauthorized access.',
  },
  {
    number: '04',
    title: 'Acceptable Use',
    content: 'To maintain a safe and reliable service, you agree not to engage in any of the following:',
    list: [
      'Use the Service for any unlawful purpose',
      'Attempt to gain unauthorized access to other users\' data or accounts',
      'Use the Service to store or transmit malicious code',
      'Reverse engineer, decompile, or disassemble any part of the Service',
      'Exceed rate limits or abuse the API',
      'Share your account credentials with third parties',
    ],
  },
  {
    number: '05',
    title: 'Database Connections',
    content: 'You are solely responsible for the databases you connect to NatureQuery. You warrant that you have the legal right to access and query those databases. NatureQuery encrypts stored credentials with AES-256 but is not liable for any unauthorized access resulting from your own security practices.',
  },
  {
    number: '06',
    title: 'Subscriptions & Billing',
    content: 'Paid plans are billed monthly via Stripe. You may cancel at any time; access continues until the end of the current billing period. Refunds are at our sole discretion. We may change pricing with 30 days\' notice.',
  },
  {
    number: '07',
    title: 'Data Ownership',
    content: 'You retain all rights to your data, queries, and results. NatureQuery does not claim ownership of any content you create or store through the Service. We may use anonymized, aggregate usage data to improve the Service.',
  },
  {
    number: '08',
    title: 'AI-Generated Content',
    content: 'SQL queries generated by the AI are provided "as-is." While we strive for accuracy, you are responsible for reviewing generated queries before execution. NatureQuery is not liable for any data loss or damage caused by executing AI-generated SQL.',
  },
  {
    number: '09',
    title: 'Limitation of Liability',
    content: 'To the maximum extent permitted by law, NatureQuery shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of data, profits, or business opportunities arising from your use of the Service.',
  },
  {
    number: '10',
    title: 'Termination',
    content: 'We may suspend or terminate your account at any time for violation of these Terms. Upon termination, your right to use the Service ceases immediately. You may export your data before termination.',
  },
  {
    number: '11',
    title: 'Changes to Terms',
    content: 'We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the new Terms. Material changes will be communicated via email or in-app notification.',
  },
]

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Nav */}
      <nav className="border-b border-border/60 bg-card/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-5xl mx-auto px-6 h-16 flex items-center gap-4">
          <Link href="/" className="p-2 hover:bg-secondary rounded-lg transition-colors">
            <ArrowLeft className="w-4 h-4" />
          </Link>
          <div className="w-px h-5 bg-border" />
          <Link href="/" className="flex items-center gap-2.5">
            <AppLogo size="sm" />
          </Link>
        </div>
      </nav>

      <div className="max-w-5xl mx-auto px-6 py-16">
        {/* Hero */}
        <div className="mb-16">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-primary/20 to-accent/20 border border-primary/20 flex items-center justify-center">
              <Scale className="w-6 h-6 text-primary" />
            </div>
            <div className="h-px flex-1 bg-gradient-to-r from-border to-transparent" />
          </div>
          <h1 className="text-4xl font-bold tracking-tight mb-4">Terms of Service</h1>
          <p className="text-lg text-muted-foreground max-w-2xl leading-relaxed">
            Please read these terms carefully before using NatureQuery. By using our service, you agree to be bound by the following terms and conditions.
          </p>
          <div className="flex items-center gap-2 mt-6 text-sm text-muted-foreground">
            <Calendar className="w-4 h-4" />
            <span>Last updated: February 8, 2026</span>
          </div>
        </div>

        {/* Two-column layout: TOC + Content */}
        <div className="lg:grid lg:grid-cols-[220px_1fr] lg:gap-16">
          {/* Sticky TOC */}
          <aside className="hidden lg:block">
            <div className="sticky top-24">
              <p className="text-xs font-semibold text-muted-foreground uppercase tracking-widest mb-4">Contents</p>
              <nav className="space-y-1">
                {sections.map((s) => (
                  <a
                    key={s.number}
                    href={`#section-${s.number}`}
                    className="flex items-center gap-2.5 py-1.5 px-2 rounded-md text-sm text-muted-foreground hover:text-foreground hover:bg-secondary transition-colors group"
                  >
                    <span className="text-xs font-mono text-primary/60 group-hover:text-primary transition-colors">{s.number}</span>
                    <span className="truncate">{s.title}</span>
                  </a>
                ))}
              </nav>
            </div>
          </aside>

          {/* Sections */}
          <div className="space-y-2">
            {sections.map((s, i) => (
              <div
                key={s.number}
                id={`section-${s.number}`}
                className="group relative rounded-2xl border border-border/60 bg-card/40 hover:bg-card/80 hover:border-border transition-all duration-200 overflow-hidden scroll-mt-24"
              >
                {/* Left accent bar */}
                <div className="absolute left-0 top-0 bottom-0 w-0.5 bg-gradient-to-b from-primary/60 to-accent/60 opacity-0 group-hover:opacity-100 transition-opacity" />

                <div className="p-7">
                  <div className="flex items-start gap-5">
                    <span className="text-xs font-mono font-bold text-primary/50 bg-primary/8 border border-primary/15 rounded-lg px-2.5 py-1.5 shrink-0 mt-0.5">
                      {s.number}
                    </span>
                    <div className="flex-1 min-w-0">
                      <h2 className="text-base font-semibold text-foreground mb-3">{s.title}</h2>
                      <p className="text-sm text-muted-foreground leading-relaxed">{s.content}</p>
                      {s.list && (
                        <ul className="mt-3 space-y-2">
                          {s.list.map((item, j) => (
                            <li key={j} className="flex items-start gap-2.5 text-sm text-muted-foreground">
                              <span className="w-1.5 h-1.5 rounded-full bg-primary/60 mt-1.5 shrink-0" />
                              {item}
                            </li>
                          ))}
                        </ul>
                      )}
                    </div>
                  </div>
                </div>
              </div>
            ))}

            {/* Contact card */}
            <div className="rounded-2xl border border-primary/20 bg-gradient-to-br from-primary/5 to-accent/5 p-7">
              <div className="flex items-start gap-5">
                <div className="w-10 h-10 rounded-xl bg-primary/10 border border-primary/20 flex items-center justify-center shrink-0">
                  <Mail className="w-5 h-5 text-primary" />
                </div>
                <div>
                  <h2 className="text-base font-semibold text-foreground mb-1">Questions about these Terms?</h2>
                  <p className="text-sm text-muted-foreground mb-3">
                    Our team is happy to clarify anything in this document.
                  </p>
                  <a
                    href="mailto:support@naturequery.com"
                    className="inline-flex items-center gap-2 text-sm font-medium text-primary hover:text-primary/80 transition-colors"
                  >
                    support@naturequery.com
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="border-t border-border/60 mt-16">
        <div className="max-w-5xl mx-auto px-6 py-8 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="text-sm text-muted-foreground">© 2026 NatureQuery. All rights reserved.</p>
          <div className="flex items-center gap-6 text-sm text-muted-foreground">
            <Link href="/privacy" className="hover:text-foreground transition-colors">Privacy Policy</Link>
            <Link href="/contact" className="hover:text-foreground transition-colors">Contact</Link>
          </div>
        </div>
      </footer>
    </div>
  )
}
